<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('users')->delete();
        
        \DB::table('users')->insert(array (
            0 => 
            array (
                'id' => 1,
                'name' => 'Super-Admin',
                'kelamin' => 'L',
                'nim' => '1111111111',
                'img' => 'user.png',
                'province_id' => NULL,
                'city_id' => NULL,
                'kecamatan_id' => NULL,
                'kelurahan_id' => NULL,
                'alamat' => 'bandung',
                'pesantren' => '-',
                't_lahir' => 'Bdng',
                'ttl' => '2023-08-25',
                'hobi' => NULL,
                'sma' => '-',
                'thn_lulus' => '2020',
                'thn_kuliah' => '2020',
                'wa' => '-',
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'role_id' => 1,
                'bio' => 'tangan terkepan dan maju kemuka!!!',
                'username' => 'super-admin',
                'slug' => 'super-admin',
                'email' => 'superadmin@gmail.com',
                'password' => '$2a$12$lfP1nqwoZC0skzUVhIEifONw7k0mvgILIrZC7YwBJ8aycvwdnfNv2',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-08-25 10:46:35',
                'updated_at' => '2023-08-25 10:47:19',
                'centang' => '0',
                'rayon_id' => '4',
                'prodi' => 'Pd Bhs. Inggris',
                'kaderisasi' => 'PKD',
                'thn_mapaba' => '2020',
                'thn_pkd' => '2020',
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => '1',
                'nonformal' => '1',
            ),
            1 =>
            array (
                'id' => 2,
                'name' => 'Admin',
                'kelamin' => 'L',
                'nim' => '2222222222',
                'img' => 'user.png',
                'province_id' => NULL,
                'city_id' => NULL,
                'kecamatan_id' => NULL,
                'kelurahan_id' => NULL,
                'alamat' => 'bandung',
                'pesantren' => '-',
                't_lahir' => 'Bdng',
                'ttl' => '2023-08-25',
                'hobi' => NULL,
                'sma' => '-',
                'thn_lulus' => '2020',
                'thn_kuliah' => '2020',
                'wa' => '-',
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'role_id' => 2,
                'bio' => 'tangan terkepan dan maju kemuka!!!',
                'username' => 'admin',
                'slug' => 'admin',
                'email' => 'admin@gmail.com',
                'password' => '$2a$12$TCr09bMIGNTEBczNOlkSE.BvcLkapqALHz9pPcRu/Z1U/UvDxhaOK',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-08-25 10:46:35',
                'updated_at' => '2023-08-25 10:47:19',
                'centang' => '0',
                'rayon_id' => '4',
                'prodi' => 'Pd Bhs. Inggris',
                'kaderisasi' => 'PKD',
                'thn_mapaba' => '2020',
                'thn_pkd' => '2020',
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => '1',
                'nonformal' => '1',
            ),
            2 =>
            array (
                'id' => 3,
                'name' => 'Pengguna',
                'kelamin' => 'L',
                'nim' => '3333333333',
                'img' => 'user.png',
                'province_id' => NULL,
                'city_id' => NULL,
                'kecamatan_id' => NULL,
                'kelurahan_id' => NULL,
                'alamat' => 'bandung',
                'pesantren' => '-',
                't_lahir' => 'Bdng',
                'ttl' => '2023-08-25',
                'hobi' => NULL,
                'sma' => '-',
                'thn_lulus' => '2020',
                'thn_kuliah' => '2020',
                'wa' => '-',
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'role_id' => 3,
                'bio' => 'tangan terkepan dan maju kemuka!!!',
                'username' => 'pengguna',
                'slug' => 'pengguna',
                'email' => 'pengguna@gmail.com',
                'password' => '$2a$12$X6qrwKAmKC/LZer/Zy8/AO/HddgFpCUI0L9.QF2LktxQBBmjvPOPe',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-08-25 10:46:35',
                'updated_at' => '2023-08-25 10:47:19',
                'centang' => '0',
                'rayon_id' => '4',
                'prodi' => 'Pd Bhs. Inggris',
                'kaderisasi' => 'PKD',
                'thn_mapaba' => '2020',
                'thn_pkd' => '2020',
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => '1',
                'nonformal' => '1',
            ),
            3 =>
            array (
                'id' => 4,
                'name' => 'Khoirul Husen',
                'kelamin' => 'L',
                'nim' => '20071011',
                'img' => 'user.png',
                'province_id' => NULL,
                'city_id' => NULL,
                'kecamatan_id' => NULL,
                'kelurahan_id' => NULL,
                'alamat' => 'Lampung',
                'pesantren' => '-',
                't_lahir' => 'Lpg',
                'ttl' => '1999-08-26',
                'hobi' => NULL,
                'sma' => '-',
                'thn_lulus' => '2018',
                'thn_kuliah' => '2020',
                'wa' => '-',
                'twitter' => NULL,
                'fb' => NULL,
                'ig' => NULL,
                'role_id' => 1,
                'bio' => 'tangan terkepan dan maju kemuka!!!',
                'username' => 'hoirulhusen08',
                'slug' => 'hoirulhusen08',
                'email' => 'hoirulhusen08@gmail.com',
                'password' => '$2a$12$X6qrwKAmKC/LZer/Zy8/AO/HddgFpCUI0L9.QF2LktxQBBmjvPOPe',
                'email_verified_at' => NULL,
                'remember_token' => NULL,
                'created_at' => '2023-08-25 10:46:35',
                'updated_at' => '2023-08-25 10:47:19',
                'centang' => '0',
                'rayon_id' => '4',
                'prodi' => 'Pd Bhs. Inggris',
                'kaderisasi' => 'PKD',
                'thn_mapaba' => '2020',
                'thn_pkd' => '2020',
                'thn_pkl' => NULL,
                'thn_pkn' => NULL,
                'informal' => '1',
                'nonformal' => '1',
            ),
        ));
        
        
    }
}